# ===========================
# 1. Base image (Development)
# ===========================
FROM node:18-bullseye

# Install build tools (penting untuk tensorflow & canvas)
RUN apt-get update && apt-get install -y \
  python3 \
  make \
  g++ \
  libcairo2-dev \
  libpango1.0-dev \
  libjpeg-dev \
  libgif-dev \
  librsvg2-dev \
  && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies (pakai devDependencies juga)
RUN npm install

# Copy seluruh source code
COPY . .

# Expose port default NestJS
EXPOSE 3000

# Jalankan NestJS dengan auto reload
CMD ["npm", "run", "start:dev"]
